name: Deploy to Robocorp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install rcc
        run: |
          curl -fsSL -o rcc https://downloads.robocorp.com/rcc/releases/v21.2.0/linux64/rcc
          chmod +x rcc

      - name: Deploy to Control Room
        run: ./rcc cloud push --account "${{ secrets.ROBOCORP_CREDENTIALS }}" --workspace "${{ secrets.ROBOCORP_WORKSPACE_ID }}" --robot "${{ secrets.ROBOCORP_ROBOT_ID }}"
