name: Deploy to Robocorp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload robot to Control Room
        uses: robocorp/action-upload-robot@v1
        with:
          workspace-key: ${{ secrets.ROBOCORP_WORKSPACE_KEY }}
          workspace-id: ${{ secrets.ROBOCORP_WORKSPACE_ID }}
          robot-id: ${{ secrets.ROBOCORP_ROBOT_ID }}
